using System;
using System.Collections.Generic;

namespace AutoPhotoEditor.Models
{
    public enum PhotoEditOperation
    {
        AutoEnhance,
        ColorGrade,
        ManualAdjust,
        Denoise,
        GeometryCorrection,
        LensCorrection,
        MaskedEnhance,
        Pipeline,
        Other
    }


    public sealed class PhotoEditJob
    {
        /// <summary>
        /// Unique ID assigned to this edit.
        /// </summary>
        public string JobId { get; init; } = string.Empty;


        /// <summary>
        /// One-based position of this operation in the committed edit timeline.
        /// </summary>
        public int Sequence { get; init; }


        /// <summary>
        /// Type of operation performed.
        /// </summary>
        public PhotoEditOperation Operation { get; init; }


        /// <summary>
        /// Original image identity for this operation.
        /// </summary>
        public string SourceImagePath { get; init; } = string.Empty;


        /// <summary>
        /// Preview output generated by the API for this timeline state.
        /// </summary>
        public string OutputImagePath { get; init; } = string.Empty;


        /// <summary>
        /// Analysis JSON returned by /auto-enhance-data.
        /// </summary>
        public string? AnalysisJson { get; init; }


        /// <summary>
        /// Serialized settings used for this operation so the action can be
        /// inspected or applied again later.
        /// </summary>
        public string? SettingsJson { get; init; }


        /// <summary>
        /// External resource required to replay this operation, such as a LUT.
        /// </summary>
        public string? ResourcePath { get; init; }

        /// <summary>
        /// Indicates that this operation was limited to selected masks.
        /// </summary>
        public bool IsMaskScoped { get; init; }

        /// <summary>
        /// Selected semantic mask names used by a mask-scoped operation.
        /// </summary>
        public IReadOnlyList<string> MaskNames { get; init; } = Array.Empty<string>();

        /// <summary>
        /// Embedded mask JSON returned by /mask-data.
        /// </summary>
        public string? MaskJson { get; init; }


        /// <summary>
        /// Previous edit this operation was based on.
        /// </summary>
        public string? ParentJobId { get; init; }


        /// <summary>
        /// Creation timestamp.
        /// </summary>
        public DateTime CreatedAt { get; init; } =
            DateTime.Now;


        /// <summary>
        /// Indicates that this history entry has been undone.
        /// </summary>
        public bool IsUndone { get; set; }
    }
}